# Generated by Django 5.1.5 on 2025-01-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokoje',
            name='liczba_osob',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokoje',
            name='czy_wolny',
            field=models.BooleanField(default=True),
        ),
    ]
